version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Set Gradle permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Gradle Tests
          command: ./gradlew test

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test